### ISSUE TITLE
Integrate Arduino core libraries for atmega328p

### ISSUE THREAD

**Issue by AaronPerl** [RPI-Void-Star/trace#29]
This will allow us to use the Arduino functions such as digitalWrite, analogRead, etc.

**Comment by droghio** [comment]
Does this mean packaging in the avr-g++ bins/libs, etc, that Arduino has by default?

**Comment by AaronPerl** [comment]
Nope, just the built in Arduino libraries (i.e. Arduino.h) so that we can have digitalWrite and pals working. We can worry about packaging avr-g++ later, but it's not part of our schedule so it should be low priority.

**Comment by droghio** [comment]
Resolved in pr #47.
